### ISSUE TITLE
How to get position object (mainly gps Lat and Lon ) by providing string address (mainly city name) ?

### ISSUE THREAD

**Issue by agrebenyuk** [jamesmontemagno/GeolocatorPlugin#140] opened 2017-08-20 21:26 UTC
Hi guys , this is just a question , not sure if this is possible to get position object (mainly gps Lat and Lon ) by providing string address (mainly city name) ?

Can you please give me an idea about how can I get it and If this is not currently supported - I would be interested if it is in your scope of work for future releases ?

Regards,
Andrey

**Comment by TonyLugg** [comment] 2017-08-21 14:02
I've asked for the same thing but I don't think it is available.

**Comment by jamesmontemagno** [comment] 2017-08-21 17:55
It is already implemented, not released. 

Duplicate of: https://github.com/jamesmontemagno/GeolocatorPlugin/issues/118

**Closed by jamesmontemagno** 2017-08-21 17:55 UTC

**Comment by agrebenyuk** [comment] 2017-08-22 01:08
Awesome news, Thanks! Can't wait to try it out !

**Comment by agrebenyuk** [comment] 2017-09-04 20:57
Hi Guys! , Any news about this feature , is there a plan to release it anytime soon ?

**Comment by jamesmontemagno** [comment] 2017-09-05 01:43
You can always grab the CI feeds: https://ci.appveyor.com/nuget/geolocatorplugin 

You would want to check commit history: https://ci.appveyor.com/project/JamesMontemagno/geolocatorplugin/history
