### ISSUE TITLE
CrossGeolocator not refreeshsirst time

### ISSUE THREAD

**Issue by brux88** [jamesmontemagno/GeolocatorPlugin#166] opened 2017-10-05 13:16 UTC
Geolocator version 3.0.4
Xamarin Forms 2.4

hello, I noticed a strange behavior
When I first install the app and there is the gps enabled.
I check to see if it has permissions, if I do not exit the dialog by telling me to authorize the app.
if I authorize and then I do  CrossGeolocator.Current.IsGeolocationEnabledalways false, I have to close the app and reopen it.

I happen to do so with the permissions first time and as if I do not update the  CrossGeolocator.Current

i added screencast
[https://drive.google.com/open?id=0B0IzbkNqehmaZEV5RDZWQWtfbEU](url)

**Comment by prashantvc** [comment] 2017-10-06 10:07
Could you share the following information? It will help us to troubleshoot the is`sue

### Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

**Comment by brux88** [comment] 2017-10-06 10:23
Version Number of Plugin: 3.0.4
Device Tested On:Samsung s8 (andorid 7)
Simulator Tested On: Emulator x86 visual studio (android 6)/ 
Version of VS:15.3.5
Version of Xamarin:2.4
Versions of other things you are using: Plugin.Permission 1.2.1

**Comment by jamesmontemagno** [comment] 2017-10-06 17:16
Duplicate of #165

**Closed by jamesmontemagno** 2017-10-06 17:16 UTC
Labels: in-review, need-more-info
